### ISSUE TITLE
Could you provide the code for the VCR dataset?

### ISSUE THREAD

**Issue by jaeyun95** [ChenRocks/UNITER#1]
i want to train vcr data!
Could you provide the code for the VCR dataset?

thank you!:)

**Comment by ChenRocks** [comment]
Thanks for your interest. We plan to release VCR but cannot guarantee a timeline.

**Comment by linjieli222** [comment]
Thank you for your interests in this project and sorry for the late reply.

Our VCR code is now available, please refer to #24.

**Comment by jaeyun95** [comment]
thank you:)
