### ISSUE TITLE
Unable to locate tools/generate_npz.py

### ISSUE THREAD

**Issue by anisha2102** [ChenRocks/UNITER#18]
While recreating the preprocessing pipeline, I am not able to locate the file generate_npz.py for image feature extraction. This file is referenced in scripts/extract_imgfeat.sh for your reference.

**Comment by ChenRocks** [comment]
Thanks for your question. The file `tools/generate_npz.py` is built into the docker image [chenrocks/butd-caffe:nlvr2](https://hub.docker.com/repository/docker/chenrocks/butd-caffe). I plan to release the github repo on how this image is built soon. In the meanwhile, you can try to copy out the whole `/src` folder from inside the image and take a look. This is modified from the original [BUTD codebase](https://github.com/peteanderson80/bottom-up-attention).

Note that extracting features using Caffe is very complex to setup and time consuming. We did a lot of manual work in the beginning of this project. The docker image provide a faithful minimal reproduction of NLVR2, which works on nvidia-418 driver and Nvidia pascal/volta GPUs.

**Comment by ChenRocks** [comment]
Please consult this [repo](https://github.com/ChenRocks/BUTD-UNITER-NLVR2) for details about building the image and the extraction script.

**Comment by FightingFighting** [comment]
@ChenRocks in here, u provide the method to extract image feature (detected). but are u going to provide the script for extracting image feature from ground-truth bboxes?
