### ISSUE TITLE
About the file to download the out-of-domain dataset

### ISSUE THREAD

**Issue by BruceW91** [ChenRocks/UNITER#21]
Hi. Could you provide the code for downloading the out-of-domain dataset (Conceptual Captions & SBU captions). 

thank you!

**Comment by ChenRocks** [comment]
Thanks for your interest in this work. Unfortunately, those files are too large that we don't have enough storage budget for anonymous downloads. Those data can be shared but only for research purpose. Please contact me by email and clearly state your research group.
