### ISSUE TITLE
About the configs for the out-of-domain and out-of-domain&in-domain pre-training

### ISSUE THREAD

**Issue by yangapku** [ChenRocks/UNITER#22]
Hi,
Currently, there is only the in-domain pre-training config in this repo. Could you please provide the config files for the out-of-domain and the out-of-domain&in-domain pre-training process? Since the detection scripts and the docker image have been already provided, we can try to generate the out-of-domain feature files and do pre-train by ourselves.

**Comment by yangapku** [comment]
Meanwhile, could you please release the config for pre-training uniter-large model as well? Thank you very much!

**Comment by ChenRocks** [comment]
I pushed the configs just now. Thanks!
