### ISSUE TITLE
nlvr2 dataset download failing.

### ISSUE THREAD

**Issue by nirajpandkar** [ChenRocks/UNITER#23]
I am facing the same problem as #2. The download breaks in the middle and restarts. Any alternative method available?

**Comment by ChenRocks** [comment]
You may try [AzCopy](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10#download-azcopy) and follow [these instructions](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-blobs?toc=/azure/storage/blobs/toc.json#download-a-file) to modify download the scripts.
