### ISSUE TITLE
Could you please provide the environment requirements ?

### ISSUE THREAD

**Issue by Zzmonica** [ChenRocks/UNITER#3]
Like the above, Could you please provide the environment requirements? I'd like to build the environment on my server without docker. Thanks!

**Comment by ChenRocks** [comment]
Thanks for your interest in this project. We do not plan to release any official conda/pip requirement file. You may take a look at the [Dockerfile](https://github.com/ChenRocks/UNITER/blob/master/Dockerfile) to get an idea of what's needed. However, we might not be able to help dependency issues if not using official docker image. Also note that pytorch version mismatch may affect the model's performance.

**Comment by Zzmonica** [comment]
For that my GPU is Tesla V100, as the ```nvcr.io/nvidia/pytorch:19.05-py3``` says :
```
Driver Requirements
Release 19.05 is based on CUDA 10.1 Update 1, which requires NVIDIA Driver release 418.xx. However, if you are running on Tesla (Tesla V100, Tesla P4, Tesla P40, or Tesla P100), you may use NVIDIA driver release 384.111+ or 410. The CUDA driver's compatibility package only supports particular drivers. For a complete list of supported drivers, see the CUDA Application Compatibility topic. For more information, see CUDA Compatibility and Upgrades.
```
so here may be the driver version Incompatible problem. What is your pytorch version ?

**Comment by ChenRocks** [comment]
I have tested the docker image on V100 with nvidia driver 418. For package versions please consult this [document](https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/rel_19-05.html#rel_19-05) from nvidia. Feel free to let me know if there's any issue with the image.

**Comment by TriLoo** [comment]
Hi, I wonder how did you complete the data preprocessing using the `chenrocks/butd-caffe:nlvr2` docker image. When I ran this container, an error happened:

```
E0407 17:53:51.580886   120 common.cpp:114] Cannot create Cublas handle. Cublas won't be available.
E0407 17:53:51.581058   120 common.cpp:121] Cannot create Curand generator. Curand won't be available.
F0407 17:53:51.581185   120 common.cpp:152] Check failed: error == cudaSuccess (35 vs. 0)  CUDA driver version is insufficient for CUDA runtime version 
```

my os: centos 7.6
cuda version: 10.1
gpu: tesla v100
gpu driver: 418.87

I also tried cuda 11.1 with gpu driver 455.32, this error still exists. 

I wonder if else have met this error or any advices ? thanks
