### ISSUE TITLE
TypeError: forward() got an unexpected keyword argument 'input_ids'

### ISSUE THREAD

**Issue by abhinavm0** [ChenRocks/UNITER#35]
Hello I am just onboarding this repo and am stuck at the following step:

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
4. Run inference for the NLVR2 task and then evaluate.

# inference
python inf_nlvr2.py --txt_db /txt/nlvr2_test1.db/ --img_db /img/nlvr2_test/ \
    --train_dir /storage/nlvr-base/ --ckpt 6500 --output_dir . --fp16
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>.

I first got an hvd error that I resolved by adding a hvd.init() in the /data/data.py after importing hvd.

But now I get the error below. Can you please let me know what I could be doing incorrectly?
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
Traceback (most recent call last):
  File "inf_nlvr2.py", line 138, in <module>
    main(args)
  File "inf_nlvr2.py", line 71, in main
    results = evaluate(model, eval_dataloader, device)
  File "/opt/conda/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 43, in decorate_no_grad
    return func(*args, **kwargs)
  File "inf_nlvr2.py", line 92, in evaluate
    scores = model(**batch, targets=None, compute_loss=False)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/apex/amp/_initialize.py", line 177, in new_fwd
    **applier(kwargs, input_caster))
TypeError: forward() got an unexpected keyword argument 'input_ids'

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

**Comment by ChenRocks** [comment]
Thanks for reporting. It should be fixed now.

For more details, this bug was introduced in this [commit](https://github.com/ChenRocks/UNITER/commit/cd546652babc8304e09dd057742d86399de8f53d#diff-ea97d53e356967e430941d4fdd588f01L244), where we change the input format for the models.

**Comment by abhinavm0** [comment]
That was very quick ChenRocks:)

Thanks for fixing this and also for all the great work!!!

Thanks,
Regards,
-Abhinav.

________________________________

**Comment by abhinavm0** [comment]
Hi ChenRocks,

I have trained the VQA after following your work here.

Is there a code to just input one single image and a corresponding question and get the answer back?

Do you have some kind of a demo like this?
https://github.com/lichengunc/MAttNet#demo

Thanks,
Regards,
-Abhinav.

________________________________
