### ISSUE TITLE
No "convert_imgdir.py"

### ISSUE THREAD

**Issue by Vimos** [ChenRocks/UNITER#4]
When I trying to reproduce preprocessing, I find this file is missing. Can you upload that file? Thanks.

**Comment by Zzmonica** [comment]
Hi, have you build the environment by docker?

**Comment by Vimos** [comment]
I guess this file is mounted to docker.

**Comment by ChenRocks** [comment]
Thanks for pointing this out. We won't be able to provide documentation about the preprocessing scripts for now so use them at our own risk.

**Comment by Zzmonica** [comment]
> I guess this file is mounted to docker.

Hi, have you installed the environment successfully? I met some problems through the docker pulling process.

**Comment by Vimos** [comment]
Yes, it was perfect.

Why not post your errors?
